version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command:
      - "CompileDaemon"
      - "-exclude-dir=.git"
      - "-exclude-dir=node_modules"
      - "-exclude-dir=web"
      - "-graceful-kill=true"
      - "-build=go build -o /go/bin/trimetric github.com/bsdavidson/trimetric/cmd/trimetric"
      - "-command=/go/bin/trimetric --migrate=true"
    depends_on:
      - kafka
      - postgres
      - redis
    image: trimetric-api
    ports:
      - "8181:80"
    secrets:
      - trimet-api-key
    volumes:
      - .:/go/src/github.com/bsdavidson/trimetric
    working_dir: /go/src/github.com/bsdavidson/trimetric

  kafka:
    image: wurstmeister/kafka:0.10.2.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      args:
        - GOOGLE_MAPS_API_KEY
    command: ["yarn", "run", "watch"]
    depends_on:
      - api
    image: trimetric-web
    ports:
      - "8080:8080"
      - "9876:9876"
    volumes:
      - ./web:/opt/trimetric/web

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

secrets:
  google-maps-api-key:
    file: ./secrets/google-maps-api-key
  trimet-api-key:
    file: ./secrets/trimet-api-key

volumes:
  pgdata: {}
